name: store_watch
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  badges: ^3.1.2
  dot_navigation_bar: ^1.0.2
  flutter:
    sdk: flutter
  flutter_pw_validator: ^1.6.0
  glass: ^1.0.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
   - assets/profile_image.jpeg
   - assets/watch_login.png
   - assets/gmail_icon.png
   - assets/background_watch.jpeg
   - assets/ads_logo.png
   - assets/
  uses-material-design: true
  fonts:
    - family: NotoSerif
      fonts:
        - asset: fonts/NotoSerif_Condensed-ExtraLight.ttf
        - asset: fonts/NotoSerif_SemiCondensed-SemiBold.ttf
    - family: Lora
      fonts:
        - asset: fonts\Lora-Regular.ttf
<<<<<<< HEAD
          



=======
      
>>>>>>> df12eb7f94ffaa15c8ceb452beac82f6a49be430
        